In [97]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler, OneHotEncoder, OrdinalEncoder
import seaborn as sns
import matplotlib.pyplot as plt

In [98]:
#  Paso 2: Cargar datos
ruta = "../data/datos_unidos.csv"  # ajusta la ruta si es necesario
df = pd.read_csv(ruta)
df.set_index('paciente_id', inplace=True)  # Establecer la columna 'ID' como índice del DataFrame
df.head()

fumador  alcohol actividad_fisica  vive  edad sexo estado_civil  \
paciente_id                                                                    
P1000000           1        1             Baja     1    69    F        Viudo   
P1000001           0        1         Moderada     0    32    M      Soltero   
P1000002           1        1             Baja     1    89    M        Viudo   
P1000003           1        1             Baja     0    78    M        Viudo   
P1000004           1        1         Moderada     1    38    F      Soltero   

            nivel_educativo    ocupacion  region  ... leucocitos  plaquetas  \
paciente_id                                       ...                         
P1000000         Secundaria     Empleado  Centro  ...       6,12     258,09   
P1000001      Universitaria     Autónomo     Sur  ...       6,97     278,32   
P1000002           Primaria  Desempleado   Norte  ...       7,54     245,35   
P1000003         Secundaria     Autónomo  Centro  ...       8,56     245,11   
P1000004           Posgrado     Autónomo   Norte  ...        8,2     234,44   

            creatinina  mut_BRCA1  mut_TP53  mut_EGFR mut_KRAS  mut_PIK3CA  \
paciente_id                                                                  
P1000000          0,97          0         0         0        0           0   
P1000001          0,85          0         0         0        0           0   
P1000002          1,59          0         0         0        0           0   
P1000003          1,26          0         0         0        1           0   
P1000004          0,88          0         0         0        0           0   

             mut_ALK  mut_BRAF  
paciente_id                     
P1000000           0         1  
P1000001           0         1  
P1000002           0         0  
P1000003           0         0  
P1000004           0         0  

[5 rows x 39 columns]

In [99]:
df.shape

(50000, 39)

In [100]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 50000 entries, P1000000 to P1049999
Data columns (total 39 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   fumador              50000 non-null  int64 
 1   alcohol              50000 non-null  int64 
 2   actividad_fisica     50000 non-null  object
 3   vive                 50000 non-null  int64 
 4   edad                 50000 non-null  int64 
 5   sexo                 50000 non-null  object
 6   estado_civil         50000 non-null  object
 7   nivel_educativo      50000 non-null  object
 8   ocupacion            50000 non-null  object
 9   region               50000 non-null  object
 10  pais_nacimiento      50000 non-null  object
 11  codigo_postal        50000 non-null  int64 
 12  ingresos_mensuales   50000 non-null  object
 13  gastos_salud         50000 non-null  int64 
 14  seguro_salud         50000 non-null  int64 
 15  deudas               50000 non-null  int64 
 16 

In [101]:
df.dtypes

fumador                 int64
alcohol                 int64
actividad_fisica       object
vive                    int64
edad                    int64
sexo                   object
estado_civil           object
nivel_educativo        object
ocupacion              object
region                 object
pais_nacimiento        object
codigo_postal           int64
ingresos_mensuales     object
gastos_salud            int64
seguro_salud            int64
deudas                  int64
tipo_empleo            object
ayudas_publicas         int64
diabetes                int64
hipertension            int64
obesidad                int64
cancer                  int64
enfermedad_cardiaca     int64
asma                    int64
epoc                    int64
glucosa                object
colesterol             object
trigliceridos          object
hemoglobina            object
leucocitos             object
plaquetas              object
creatinina             object
mut_BRCA1               int64
mut_TP53  

In [102]:
df.columns


Index(['fumador', 'alcohol', 'actividad_fisica', 'vive', 'edad', 'sexo',
       'estado_civil', 'nivel_educativo', 'ocupacion', 'region',
       'pais_nacimiento', 'codigo_postal', 'ingresos_mensuales',
       'gastos_salud', 'seguro_salud', 'deudas', 'tipo_empleo',
       'ayudas_publicas', 'diabetes', 'hipertension', 'obesidad', 'cancer',
       'enfermedad_cardiaca', 'asma', 'epoc', 'glucosa', 'colesterol',
       'trigliceridos', 'hemoglobina', 'leucocitos', 'plaquetas', 'creatinina',
       'mut_BRCA1', 'mut_TP53', 'mut_EGFR', 'mut_KRAS', 'mut_PIK3CA',
       'mut_ALK', 'mut_BRAF'],
      dtype='object')

In [103]:
df.head(3)

fumador  alcohol actividad_fisica  vive  edad sexo estado_civil  \
paciente_id                                                                    
P1000000           1        1             Baja     1    69    F        Viudo   
P1000001           0        1         Moderada     0    32    M      Soltero   
P1000002           1        1             Baja     1    89    M        Viudo   

            nivel_educativo    ocupacion  region  ... leucocitos  plaquetas  \
paciente_id                                       ...                         
P1000000         Secundaria     Empleado  Centro  ...       6,12     258,09   
P1000001      Universitaria     Autónomo     Sur  ...       6,97     278,32   
P1000002           Primaria  Desempleado   Norte  ...       7,54     245,35   

            creatinina  mut_BRCA1  mut_TP53  mut_EGFR mut_KRAS  mut_PIK3CA  \
paciente_id                                                                  
P1000000          0,97          0         0         0        0           0   
P1000001          0,85          0         0         0        0           0   
P1000002          1,59          0         0         0        0           0   

             mut_ALK  mut_BRAF  
paciente_id                     
P1000000           0         1  
P1000001           0         1  
P1000002           0         0  

[3 rows x 39 columns]

In [104]:
df.describe()

fumador  alcohol          vive          edad  codigo_postal  \
count  50000.000000  50000.0  50000.000000  50000.000000    50000.00000   
mean       0.364360      1.0      0.871680     53.398700    50001.09824   
std        0.481255      0.0      0.334449     20.799006    28692.22255   
min        0.000000      1.0      0.000000     18.000000      501.00000   
25%        0.000000      1.0      1.000000     35.000000    25049.75000   
50%        0.000000      1.0      1.000000     53.000000    49844.00000   
75%        1.000000      1.0      1.000000     71.000000    74866.25000   
max        1.000000      1.0      1.000000     89.000000    99943.00000   

       gastos_salud  seguro_salud        deudas  ayudas_publicas  \
count  50000.000000       50000.0  50000.000000          50000.0   
mean     228.762000           1.0      0.192720              1.0   
std       88.941023           0.0      0.394439              0.0   
min      150.000000           1.0      0.000000              1.0   
25%      150.000000           1.0      0.000000              1.0   
50%      250.000000           1.0      0.000000              1.0   
75%      250.000000           1.0      0.000000              1.0   
max      550.000000           1.0      1.000000              1.0   

           diabetes  ...  enfermedad_cardiaca     asma          epoc  \
count  50000.000000  ...         50000.000000  50000.0  50000.000000   
mean       0.212540  ...             0.194140      0.0      0.036220   
std        0.409109  ...             0.395541      0.0      0.186839   
min        0.000000  ...             0.000000      0.0      0.000000   
25%        0.000000  ...             0.000000      0.0      0.000000   
50%        0.000000  ...             0.000000      0.0      0.000000   
75%        0.000000  ...             0.000000      0.0      0.000000   
max        1.000000  ...             1.000000      0.0      1.000000   

          mut_BRCA1      mut_TP53      mut_EGFR      mut_KRAS    mut_PIK3CA  \
count  50000.000000  50000.000000  50000.000000  50000.000000  50000.000000   
mean       0.098940      0.099860      0.102120      0.100500      0.101340   
std        0.298584      0.299816      0.302809      0.300669      0.301781   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        0.000000      0.000000      0.000000      0.000000      0.000000   
50%        0.000000      0.000000      0.000000      0.000000      0.000000   
75%        0.000000      0.000000      0.000000      0.000000      0.000000   
max        1.000000      1.000000      1.000000      1.000000      1.000000   

            mut_ALK      mut_BRAF  
count  50000.000000  50000.000000  
mean       0.103380      0.100300  
std        0.304458      0.300403  
min        0.000000      0.000000  
25%        0.000000      0.000000  
50%        0.000000      0.000000  
75%        0.000000      0.000000  
max        1.000000      1.000000  

[8 rows x 23 columns]

In [105]:
df.isnull().sum()

fumador                0
alcohol                0
actividad_fisica       0
vive                   0
edad                   0
sexo                   0
estado_civil           0
nivel_educativo        0
ocupacion              0
region                 0
pais_nacimiento        0
codigo_postal          0
ingresos_mensuales     0
gastos_salud           0
seguro_salud           0
deudas                 0
tipo_empleo            0
ayudas_publicas        0
diabetes               0
hipertension           0
obesidad               0
cancer                 0
enfermedad_cardiaca    0
asma                   0
epoc                   0
glucosa                0
colesterol             0
trigliceridos          0
hemoglobina            0
leucocitos             0
plaquetas              0
creatinina             0
mut_BRCA1              0
mut_TP53               0
mut_EGFR               0
mut_KRAS               0
mut_PIK3CA             0
mut_ALK                0
mut_BRAF               0
dtype: int64

In [106]:
df['tipo_empleo'].unique()

array(['Público', 'Temporal', 'Desempleado', 'Privado', 'Autónomo'],
      dtype=object)

In [107]:
df['codigo_postal'].unique()

array([98471, 23903, 20094, ...,  8356,  2946, 25957], dtype=int64)

In [108]:
df['region'].unique()

array(['Centro', 'Sur', 'Norte', 'Oeste', 'Este'], dtype=object)

In [109]:
df['ocupacion'].unique()

array(['Empleado', 'Autónomo', 'Desempleado', 'Jubilado'], dtype=object)

In [110]:
df['asma'].unique()

array([0], dtype=int64)

In [111]:
df.drop(columns=['asma'], inplace=True)

In [112]:
df['pais_nacimiento'].unique()

array(['Indonesia', 'Brazil', 'Saint Pierre and Miquelon', 'Chile',
       'Cuba', 'American Samoa', 'Montenegro', 'Cameroon', 'Barbados',
       'Slovenia', 'Greenland', 'China', 'Somalia', 'Senegal', 'Korea',
       'Palau', 'Swaziland', 'Antigua and Barbuda',
       'Holy See (Vatican City State)', 'Netherlands',
       'Equatorial Guinea', 'Samoa', 'Montserrat', 'San Marino',
       'Cayman Islands', 'Malta', 'Tuvalu', 'Benin',
       'United States of America', 'Bahamas', 'Cape Verde', 'Kazakhstan',
       'French Guiana', 'Switzerland', "Cote d'Ivoire", 'Azerbaijan',
       'Timor-Leste', 'Gibraltar', 'Vanuatu', 'Malawi',
       'Saint Vincent and the Grenadines', 'Algeria', 'France',
       'Honduras', 'Nigeria', 'Turkmenistan', 'Isle of Man', 'Fiji',
       'Singapore', 'Kenya', 'Sweden', 'Qatar', 'Ethiopia', 'Panama',
       'Gambia', 'Liechtenstein', 'Finland', 'Serbia', 'Kuwait',
       'Iceland', 'Syrian Arab Republic', 'Australia', 'Greece',
       'British Indian Ocean Te

In [113]:
mapa_continente_nacimiento = {
    'África': [
        'Algeria', 'Angola', 'Benin', 'Botswana', 'Burkina Faso', 'Burundi',
        'Cameroon', 'Cape Verde', 'Central African Republic', 'Chad', 'Comoros',
        'Congo', "Cote d'Ivoire", 'Djibouti', 'Egypt', 'Equatorial Guinea',
        'Eritrea', 'Ethiopia', 'Gabon', 'Gambia', 'Ghana', 'Guinea',
        'Guinea-Bissau', 'Kenya', 'Lesotho', 'Liberia', 'Libyan Arab Jamahiriya',
        'Madagascar', 'Malawi', 'Mali', 'Mauritania', 'Mauritius', 'Mayotte',
        'Morocco', 'Mozambique', 'Namibia', 'Niger', 'Nigeria', 'Reunion',
        'Rwanda', 'Sao Tome and Principe', 'Senegal', 'Seychelles', 'Sierra Leone',
        'Somalia', 'South Africa', 'Sudan', 'Swaziland', 'Tanzania', 'Togo',
        'Tunisia', 'Uganda', 'Western Sahara', 'Zambia', 'Zimbabwe', 
        'British Indian Ocean Territory (Chagos Archipelago)', 'Saint Helena'
    ],
    'América': [
        'Antigua and Barbuda', 'Argentina', 'Bahamas', 'Barbados', 'Belize',
        'Bermuda', 'Bolivia', 'Brazil', 'Canada', 'Cayman Islands', 'Chile',
        'Colombia', 'Costa Rica', 'Cuba', 'Dominica', 'Dominican Republic',
        'Ecuador', 'El Salvador', 'French Guiana', 'Grenada', 'Guadeloupe',
        'Guatemala', 'Guyana', 'Haiti', 'Honduras', 'Jamaica', 'Martinique',
        'Mexico', 'Montserrat', 'Nicaragua', 'Panama', 'Paraguay', 'Peru',
        'Puerto Rico', 'Saint Barthelemy', 'Saint Kitts and Nevis',
        'Saint Lucia', 'Saint Martin', 'Saint Pierre and Miquelon',
        'Saint Vincent and the Grenadines', 'Suriname', 'Trinidad and Tobago',
        'Turks and Caicos Islands', 'United States of America',
        'Uruguay', 'Venezuela', 'British Virgin Islands', 'United States Virgin Islands', 
        'Greenland', 'United States Minor Outlying Islands', 'Netherlands Antilles', 
        'Aruba', 'Falkland Islands (Malvinas)', 'Anguilla'
    ],
    'Asia': [
        'Afghanistan', 'Armenia', 'Azerbaijan', 'Bahrain', 'Bangladesh', 'Bhutan',
        'Brunei Darussalam', 'Cambodia', 'China', 'Cyprus', 'Georgia', 'India',
        'Indonesia', 'Iran', 'Iraq', 'Israel', 'Japan', 'Jordan', 'Kazakhstan',
        'Korea', 'Kuwait', 'Kyrgyz Republic', "Lao People's Democratic Republic",
        'Lebanon', 'Malaysia', 'Maldives', 'Mongolia', 'Myanmar', 'Nepal',
        'Oman', 'Pakistan', 'Palestinian Territory', 'Philippines', 'Qatar',
        'Saudi Arabia', 'Singapore', 'Sri Lanka', 'Syrian Arab Republic',
        'Tajikistan', 'Thailand', 'Timor-Leste', 'Turkey', 'Turkmenistan',
        'United Arab Emirates', 'Uzbekistan', 'Vietnam', 'Yemen', 'Taiwan', 
        'Hong Kong', 'Macao'
    ],
    'Europa': [
        'Albania', 'Andorra', 'Austria', 'Belarus', 'Belgium', 'Bosnia and Herzegovina',
        'Bulgaria', 'Croatia', 'Czech Republic', 'Denmark', 'Estonia', 'Faroe Islands',
        'Finland', 'France', 'Germany', 'Gibraltar', 'Greece', 'Guernsey', 
        'Holy See (Vatican City State)', 'Hungary', 'Iceland', 'Ireland', 'Isle of Man', 
        'Italy', 'Jersey', 'Latvia', 'Liechtenstein', 'Lithuania', 'Luxembourg', 
        'Malta', 'Moldova', 'Monaco', 'Montenegro', 'Netherlands', 'North Macedonia', 
        'Norway', 'Poland', 'Portugal', 'Romania', 'Russian Federation', 'San Marino', 
        'Serbia', 'Slovakia (Slovak Republic)', 'Slovenia', 'Spain', 'Sweden', 
        'Switzerland', 'Ukraine', 'United Kingdom'
    ],
    'Oceanía': [
        'American Samoa', 'Australia', 'Christmas Island', 'Cocos (Keeling) Islands',
        'Cook Islands', 'Fiji', 'French Polynesia', 'Guam', 'Kiribati', 'Marshall Islands',
        'Micronesia', 'Nauru', 'New Caledonia', 'New Zealand', 'Niue', 'Norfolk Island',
        'Northern Mariana Islands', 'Palau', 'Papua New Guinea', 'Pitcairn Islands',
        'Samoa', 'Solomon Islands', 'Tokelau', 'Tonga', 'Tuvalu', 'Vanuatu',
        'Wallis and Futuna'
    ],
    'Antártida': [
        'Antarctica (the territory South of 60 deg S)',
        'Bouvet Island (Bouvetoya)',
        'French Southern Territories',
        'Heard Island and McDonald Islands',
        'South Georgia and the South Sandwich Islands',
        'Svalbard & Jan Mayen Islands'
    ]
}

In [114]:
def assign_continente_nacimiento(pais_nacimiento):
    for continente_nacimiento, paises in mapa_continente_nacimiento.items():
        if pais_nacimiento in paises:
            return continente_nacimiento
    return 'Desconocida'

In [115]:
df['continente_nacimiento'] = df['pais_nacimiento'].map(assign_continente_nacimiento)

In [116]:
df['continente_nacimiento'].unique()

array(['Asia', 'América', 'Oceanía', 'Europa', 'África', 'Antártida'],
      dtype=object)

In [117]:
pais_sin_continente = df[df['continente_nacimiento'].isnull()]['pais_nacimiento'].unique()

# Mostrar la lista de países con 'continent' como None
print("Lista de países con 'continent' como None:")
print(pais_sin_continente)

Lista de países con 'continent' como None:
[]


In [118]:
df.drop(columns=['pais_nacimiento'], inplace=True)  # Eliminar la columna 'Provincia'

In [119]:
df.head()

fumador  alcohol actividad_fisica  vive  edad sexo estado_civil  \
paciente_id                                                                    
P1000000           1        1             Baja     1    69    F        Viudo   
P1000001           0        1         Moderada     0    32    M      Soltero   
P1000002           1        1             Baja     1    89    M        Viudo   
P1000003           1        1             Baja     0    78    M        Viudo   
P1000004           1        1         Moderada     1    38    F      Soltero   

            nivel_educativo    ocupacion  region  ...  plaquetas creatinina  \
paciente_id                                       ...                         
P1000000         Secundaria     Empleado  Centro  ...     258,09       0,97   
P1000001      Universitaria     Autónomo     Sur  ...     278,32       0,85   
P1000002           Primaria  Desempleado   Norte  ...     245,35       1,59   
P1000003         Secundaria     Autónomo  Centro  ...     245,11       1,26   
P1000004           Posgrado     Autónomo   Norte  ...     234,44       0,88   

             mut_BRCA1  mut_TP53  mut_EGFR mut_KRAS  mut_PIK3CA  mut_ALK  \
paciente_id                                                                
P1000000             0         0         0        0           0        0   
P1000001             0         0         0        0           0        0   
P1000002             0         0         0        0           0        0   
P1000003             0         0         0        1           0        0   
P1000004             0         0         0        0           0        0   

             mut_BRAF  continente_nacimiento  
paciente_id                                   
P1000000            1                   Asia  
P1000001            1                América  
P1000002            0                América  
P1000003            0                   Asia  
P1000004            0                América  

[5 rows x 38 columns]

In [120]:
df['alcohol'].unique()

array([1], dtype=int64)

In [121]:
df['seguro_salud'].unique()

array([1], dtype=int64)

In [122]:
df['ayudas_publicas'].unique()

array([1], dtype=int64)

In [123]:
df.drop(columns=['ayudas_publicas'], inplace=True)

In [124]:
df.drop(columns=['alcohol'], inplace=True)

In [125]:
df.drop(columns=['seguro_salud'], inplace=True)

In [126]:
# --- 1. Codificación OneHot ---
onehot_cols = ['estado_civil', 'tipo_empleo', 'ocupacion']
columnas_a_codificar = [col for col in onehot_cols if col in df.columns]

if columnas_a_codificar:
    df = pd.get_dummies(df, columns=columnas_a_codificar, drop_first=True)

# --- 2. Conversión de columnas con comas ---
for col in df.columns:
    if df[col].dtype == 'object':
        muestras = df[col].dropna().astype(str).head(5)
        if muestras.str.contains(r'^\d+,\d+$').any():  # ejemplo: '88,6'
            df[col] = df[col].str.replace(',', '.').astype(float)

# --- 3. Mostrar columnas no convertibles (tipo texto real, como 'sexo') ---
no_convertibles = df.select_dtypes(include='object').columns.tolist()
if no_convertibles:
    print("Estas columnas aún tienen texto y no se pueden convertir:", no_convertibles)

# --- 4. Convertir el resto a float ---
df[df.select_dtypes(exclude='object').columns] = df.select_dtypes(exclude='object').astype(float)

Estas columnas aún tienen texto y no se pueden convertir: ['actividad_fisica', 'sexo', 'nivel_educativo', 'region', 'continente_nacimiento']


In [127]:
df['actividad_fisica'].unique()

array(['Baja', 'Moderada', 'Alta'], dtype=object)

In [ ]:
ordinal_cols = ['nivel_educativo', 'actividad_fisica']

orden_nivel_educativo = ['Primaria', 'Secundaria', 'Universitaria', 'Posgrado']
orden_actividad_fisica = ['Baja', 'Moderada', 'Alta']

oe = OrdinalEncoder(categories=[orden_nivel_educativo, orden_actividad_fisica])



In [129]:
df[ordinal_cols] = oe.fit_transform(df[ordinal_cols])

In [130]:
df.head()

fumador  actividad_fisica  vive  edad sexo  nivel_educativo  \
paciente_id                                                                
P1000000         1.0               0.0   1.0  69.0    F              1.0   
P1000001         0.0               1.0   0.0  32.0    M              2.0   
P1000002         1.0               0.0   1.0  89.0    M              0.0   
P1000003         1.0               0.0   0.0  78.0    M              1.0   
P1000004         1.0               1.0   1.0  38.0    F              3.0   

             region  codigo_postal  ingresos_mensuales  gastos_salud  ...  \
paciente_id                                                           ...   
P1000000     Centro        98471.0             2699.72         450.0  ...   
P1000001        Sur        23903.0             3403.55         150.0  ...   
P1000002      Norte        20094.0             2422.41         150.0  ...   
P1000003     Centro        55575.0             1695.42         450.0  ...   
P1000004      Norte        20826.0             1709.51         150.0  ...   

             estado_civil_Divorciado  estado_civil_Soltero  \
paciente_id                                                  
P1000000                         0.0                   0.0   
P1000001                         0.0                   1.0   
P1000002                         0.0                   0.0   
P1000003                         0.0                   0.0   
P1000004                         0.0                   1.0   

             estado_civil_Viudo  tipo_empleo_Desempleado  tipo_empleo_Privado  \
paciente_id                                                                     
P1000000                    1.0                      0.0                  0.0   
P1000001                    0.0                      0.0                  0.0   
P1000002                    1.0                      1.0                  0.0   
P1000003                    1.0                      0.0                  0.0   
P1000004                    0.0                      0.0                  0.0   

             tipo_empleo_Público  tipo_empleo_Temporal  ocupacion_Desempleado  \
paciente_id                                                                     
P1000000                     1.0                   0.0                    0.0   
P1000001                     0.0                   1.0                    0.0   
P1000002                     0.0                   0.0                    1.0   
P1000003                     0.0                   1.0                    0.0   
P1000004                     0.0                   1.0                    0.0   

             ocupacion_Empleado  ocupacion_Jubilado  
paciente_id                                          
P1000000                    1.0                 0.0  
P1000001                    0.0                 0.0  
P1000002                    0.0                 0.0  
P1000003                    0.0                 0.0  
P1000004                    0.0                 0.0  

[5 rows x 42 columns]